### ISSUE TITLE
Best practices for reconnecting to the HSM after a reset?

### ISSUE THREAD

**Issue by woodruffw** [iqlusioninc/yubihsm.rs#14]
First of all, thanks a ton for this library! It's been invaluable.

Is there any guidance/best practices available for correctly reconnecting to the HSM after performing a factory reset (i.e with `client.reset_device()`)? I'm running into an issue where creating a brand new `Client` (no shared state other than the `UsbConfig`, which doesn't contain bus or address information) after that reset causes an error during USB device enumeration:

```
Error(Context { kind: ProtocolError, source: Some(Error(Context { kind: ProtocolError, source: Some(Error(Context { kind: UsbError, source: Some(Message("USB(bus=20,addr=27): error opening device: No such device (it may have been disconnected)"))
```

The error happens here, during iteration over discovered devices:

https://github.com/iqlusioninc/yubihsm.rs/blob/2952153a1a9b0bd2bba1d78223e2f6645c95bb65/src/connector/usb/device.rs#L92

That code calls `rusb`'s `GlobalContext::default().devices()` to get the list of active devices, which (AFAICT) is a straightforward wrapper around `libusb_get_device_list`. That in turn should always be up-to-date, but there may be some caching that I haven't noticed.

**Comment by tarcieri** [comment]
There's a [`reset_device_and_reconnect`](https://docs.rs/yubihsm/0.32.0/yubihsm/client/struct.Client.html#method.reset_device_and_reconnect) method.

**Comment by woodruffw** [comment]
Thanks for the quick response. I get the same error even with `reset_device_and_reconnect` (with a 30 second timeout).

My current best guess is that this might be related to `rusb`'s use of `std::Once` when building the `GlobalContext`:

```rust
impl UsbContext for GlobalContext {
    fn as_raw(&self) -> *mut libusb_context {
        static mut USB_CONTEXT: *mut libusb_context = ptr::null_mut();
        static ONCE: Once = Once::new();

        ONCE.call_once(|| {
            let mut context = mem::MaybeUninit::<*mut libusb_context>::uninit();
            unsafe {
                USB_CONTEXT = match libusb_init(context.as_mut_ptr()) {
                    0 => context.assume_init(),
                    err => panic!(
                        "Can't init Global usb context, error {:?}",
                        error::from_libusb(err)
                    ),
                }
            };
        });
        // Clone data that is safe to use concurrently.
        unsafe { USB_CONTEXT }
    }
}
```

(https://github.com/a1ien/rusb/blob/ea85b7f9a3bd2a5a1f2f355727678aa504124afd/src/context.rs#L164)

The `libusb` docs aren't clear on whether a new context is needed to consistently refresh the device list on all backends (e.g. backends that are poll-based, like macOS's). I'll keep digging into it.

**Comment by woodruffw** [comment]
Update: I was able to fix this by replacing usage of `rusb`'s `GlobalContext` with `Context`, which should properly refresh the device list on all libusb backends. I'll create a PR in a bit.

**Comment by woodruffw** [comment]
Opened #15.
