### ISSUE TITLE
Signing using ecdsa::Signature results in compilation error

### ISSUE THREAD

**Issue by wellcaffeinated** [iqlusioninc/yubihsm.rs#176]
Hi. I'm having a lot of trouble using this library. I've managed to do a lot with it but keep running into confusion when attempting to sign with ecdsa.

Here's the compilation error I'm running into:

> type mismatch resolving `<sha2::Sha512 as sha2::Digest>::OutputSize == sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UTerm, sha2::digest::consts::B1>, sha2::digest::consts::B0>, sha2::digest::consts::B0>, sha2::digest::consts::B0>, sha2::digest::consts::B0>, sha2::digest::consts::B0>`
> 
> expected struct `sha2::digest::generic_array::typenum::UInt`, found struct `sha2::digest::generic_array::typenum::UTerm`
> 
> note: expected struct `sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UTerm, sha2::digest::consts::B1>, sha2::digest::consts::B0>, _>, _>, _>, _>, _>`
>          found struct `sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UInt<sha2::digest::generic_array::typenum::UTerm, sha2::digest::consts::B1>, _>, _>, _>, _>, _>`
> note: required because of the requirements on the impl of `yubihsm::asymmetric::signature::DigestSigner<sha2::Sha512, yubihsm::ecdsa::Signature<yubihsm::ecdsa::NistP256>>` for `yubihsm::ecdsa::Signer<yubihsm::ecdsa::NistP256>`rustc(E0271)
> signing.rs(79, 16): expected struct `sha2::digest::generic_array::typenum::UInt`, found struct `sha2::digest::generic_array::typenum::UTerm`

I'm trying to do this:

```
let signer = ecdsa::Signer::<ecdsa::NistP256>::create(client, key).unwrap()
let mut digest = sha2::Sha512::new();
digest.update(v);
signer.try_sign_digest(digest)? // ERROR HERE
  .to_asn1()
  .as_bytes()
```

Maybe i'm doing this wrong, and would really appreciate a hint as to how to do this right if that's the case. I've been working on this in a round about way for a long time. Might also be worth adding some example documentation because even though the docs say "We recommend using the ecdsa::Signer type instead, which provides a high-level, well-typed, misuse resistant API."... the API is, at least in my case, resistant to plain old use.

thanks in advance

**Comment by wellcaffeinated** [comment]
Looks like i was using the wrong hash function. Sorry for imposing my confusion. 

I do think some little example docs would be really great though and helpful for others. Perhaps some indication in the signing functions/curves pointing to which hash functions they accept.

Thanks!

**Comment by tony-iqlusion** [comment]
Note that there is an [`ecdsa::nistp256::Signer`](https://docs.rs/yubihsm/0.38.0/yubihsm/ecdsa/nistp256/type.Signer.html) type which impls the [`signature::Signer`](https://docs.rs/yubihsm/0.38.0/yubihsm/ecdsa/struct.Signer.html#impl-Signer%3CS%3E) trait.

When that trait is in scope, you can just do `signer.try_sign(v)` and not worry about the specific hash function (it will use SHA-256 by default).

I agree this could use more documentation.

**Comment by wellcaffeinated** [comment]
Thanks for that.
If you have a sec, I'm still actually confused. There are a bunch of things called Signer and i don't know how to get the scope right.

I imagine I'd do this:

```
use yubihsm::asymmetric::signature::{Signer};
let signer = ecdsa::nistp256::Signer::create(client, key_id).unwrap();

signer.try_sign(v);
```

But i get the following:

> the trait bound `yubihsm::ecdsa::Signature<yubihsm::ecdsa::NistP256>: yubihsm::asymmetric::signature::PrehashSignature` is not satisfied
> 
> the trait `yubihsm::asymmetric::signature::PrehashSignature` is not implemented for `yubihsm::ecdsa::Signature<yubihsm::ecdsa::NistP256>`
> 
> note: required because of the requirements on the impl of `yubihsm::asymmetric::signature::Signer<yubihsm::ecdsa::Signature<yubihsm::ecdsa::NistP256>>` for `yubihsm::ecdsa::Signer<yubihsm::ecdsa::NistP256>`rustc(E0277)
> signing.rs(74, 12): the trait `yubihsm::asymmetric::signature::PrehashSignature` is not implemented for `yubihsm::ecdsa::Signature<yubihsm::ecdsa::NistP256>`

**Comment by tony-iqlusion** [comment]
It looks like the problem is the `sha256` feature of the `p256` crate isn't getting activated by the `yubihsm` crate, which is a small bug.

You can work around it by adding the following to `[dependencies]` in `Cargo.toml`:

```toml
p256 = { version = "0.7", features = ["ecdsa", "sha256"] }
```

**Comment by tony-iqlusion** [comment]
This upstream fix in the `p256` crate should fix the feature gating problems in the next minor release (the `yubihsm` crate itself will also have to update):

https://github.com/RustCrypto/elliptic-curves/pull/324

**Comment by wellcaffeinated** [comment]
Oh thank you! I was so confused as to why that wasn't working. It's working just fine now.
