### ISSUE TITLE
USB error: Operation timed out

### ISSUE THREAD

**Issue by wellcaffeinated** [iqlusioninc/yubihsm.rs#267]
Hey there, I've been successfully using this awesome library for ECDSA signing, but just now tried to do the same with RSA PKCS and i'm running into the following error:

> USB error: Operation timed out
> 
> Caused by:
>     0: protocol error: USB error: Operation timed out
>     1: USB error: Operation timed out
>     2: Operation timed out

The code that is causing it is:

```rust
hsm_client.generate_asymmetric_key(
  cfg.signing_key_address,
  "My Key".into(),
  yubihsm::Domain::DOM1,
  yubihsm::Capability::SIGN_PKCS,
  yubihsm::asymmetric::Algorithm::Rsa2048
)?;
```

I can provide more debug info if you let me know what you need.
Any ideas?

**Comment by wellcaffeinated** [comment]
(additionally, this "timed out" error happens without delay)

**Comment by tony-iqlusion** [comment]
The default timeout for all USB operations is 1 second.

It would be rather unsurprising that RSA key generation takes longer than that.

The timeout is configurable via the [`UsbConfig`](https://docs.rs/yubihsm/0.39.0/yubihsm/connector/usb/struct.UsbConfig.html) struct, which you can pass as a parameter to [`UsbConnector`](https://docs.rs/yubihsm/0.39.0/yubihsm/connector/usb/struct.UsbConnector.html).

You could potentially try turning it up and see if it fixes the issue.

If I have some time I'll see if I can reproduce this and potentially raise the default USB timeout accordingly.

**Comment by wellcaffeinated** [comment]
Ahhh that was it. Thanks. I changed it to 5s and the issue was gone.
Now happily signing with RSA. Thanks!

**Comment by wellcaffeinated** [comment]
(...which, BTW works! I know you have it untested currently. I'll need to use this in production eventually so I'd love to help get the RSA functionality out of the `untested` flag if i can )

**Comment by tony-iqlusion** [comment]
Awesome! If it seems to be working I can go ahead and mark it as tested.

Perhaps it would also make sense to turn the default timeout up to 5 seconds.

**Comment by wellcaffeinated** [comment]
Yeah i noticed the key generation timed out once at 5s so, maybe longer? I'm not sure the repercussions of having a longer default timeout

**Comment by tony-iqlusion** [comment]
The timeout was chosen somewhat arbitrarily. I can raise it to 10 by default.

**Comment by wellcaffeinated** [comment]
@tony-iqlusion Just wanted to say THANK YOU! I only just noticed the http-server feature after many, many struggles with yubihsm-connect. I'm so glad i don't have to use it anymore. 🎉
