### ISSUE TITLE
Sign PKCS1 command

### ISSUE THREAD

**Issue by ipaljak-tbtl** [iqlusioninc/yubihsm.rs#39]
Hi,

my name is Ivan and I'm a software engineer at TBTL. In order to deploy our platform in production, we need to sign certain things using PKCS1 with a key we intend to keep in a YubiHSM 2 device. Naturally, we are considering using your crate to do so.

I see from the table and source code comments that this command is untested in the main implementation and unsupported with MockHSM. Could you share some more details on that part? For example, what type of testing has been done thus far, what additional testing would you like to have and what can we do to help.

**Comment by tony-iqlusion** [comment]
Right now the command should theoretically be wrapped, but it has never been tested/verified live against a YubiHSM2 device (our usages for signature-related purposes are ECDSA and Ed25519 exclusively).

In theory it should work, and if it doesn't, we can help debug. It'd be great if you can confirm if it is or is not working and we'll update the table accordingly.

**Comment by ipaljak-tbtl** [comment]
Thanks, I'll let you know if we try it out on a live device.
